apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ticloud-manager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: ticloud-manager
        app: ticloud-manager
    spec:
      containers:
      - name: ticloud-manager
        image: localhost:5000/ticloud-manager:latest
        command: ["/usr/local/bin/ticloud-manager"]
        args: ["-L=debug"]
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
      volumes:
      - name: timezone
        hostPath:
          path: /etc/localtime
